### ISSUE TITLE
html2canvas

### ISSUE THREAD

**Issue by iamdman** [Devleed/instant-nft#1]
Hi there,

Have you been able to get html2canvas working without CSP errors using manifest 3?  I was reviewing your code but it looks incomplete so I was not able to test the html2canvas functionality.

Thanks.

**Comment by Devleed** [comment]
Hey,

Yes the code is incomplete because of the CSP errors. I was unable to make it work on most of the websites. If you have found a fix then please do let me know.

Thanks.

**Comment by iamdman** [comment]
I may try to use native chrome API: captureVisibleTab

This is quite old but the method still exists.  https://louisrli.github.io/blog/2013/01/16/javascript-canvas-screenshot/#.Yz1_RXbMKw4

**Comment by Devleed** [comment]
Thanks for this. Will give it a try.
